<form method="post" class="col-md-12">
    <div class="col-md-4">Uživatelské jméno</div>
        <div class="col-md-8"><input name="userName" type="text"></div>
    <div class="col-md-4">Heslo</div>
        <div class="col-md-8"><input name="passW" type="password"></div>
    <div class="col-md-8"></div>
        <div class="col-md-4"><input class="btn" type="submit" value="Přihlásit"></div>
    <div class="lista">Nejste registrovaní?<a href="registration">Registrace</a></div>
</form>