<!DOCTYPE html>
<html lang="cz" xmlns:https="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link rel=stylesheet type="text/css" href="resources/styles/bootstrap-4.0.0-alpha.6/dist/css/bootstrap.css"/>
    <link rel=stylesheet type="text/css" href="../resources/styles/style.css"/>


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel=stylesheet type="text/css" href="resources/styles/style.css"/>

    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $key_words ?>" />
</head>
<body>
<!--<nav class="navbar navbar-inverse">-->
<!--    <div class="container-fluid">-->
<!--        <div class="navbar-header">-->
<!--            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--                <span class="icon-bar"></span>-->
<!--            </button>-->
<!--            <a class="navbar-brand" href="#">Logo</a>-->
<!--        </div>-->
<!--        <div class="collapse navbar-collapse" id="myNavbar">-->
<!--            <ul class="nav navbar-nav">-->
<!--                <li class="active"><a href="#">Home</a></li>-->
<!--                <li><a href="#">About</a></li>-->
<!--                <li><a href="#">Projects</a></li>-->
<!--                <li><a href="#">Contact</a></li>-->
<!--            </ul>-->
<!--            <ul class="nav navbar-nav navbar-right">-->
<!--                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
<!--</nav>-->
<!---->
<!--<div class="container-fluid text-center">-->
<!--    <div class="row content">-->
<!--        <div class="col-sm-2 sidenav">-->
<!--            <p><a href="#">Link</a></p>-->
<!--            <p><a href="#">Link</a></p>-->
<!--            <p><a href="#">Link</a></p>-->
<!--        </div>-->
<!--        <div class="col-sm-8 text-left">-->
<!--            <h1>Welcome</h1>-->
<!--            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>-->
<!--            <hr>-->
<!--            <h3>Test</h3>-->
<!--            <p>Lorem ipsum...</p>-->
<!--        </div>-->
<!--        <div class="col-sm-2 sidenav">-->
<!--            <div class="well">-->
<!--                <p>ADS</p>-->
<!--            </div>-->
<!--            <div class="well">-->
<!--                <p>ADS</p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="container">
    <div class="row" style="margin-top: 1em">
        <div class="col-md-4 lista" style="text-align: right">
            <h1><a href="intro">Vocabulary Practice</a></h1>
            <!--<hr class="horizontalLine">-->
        </div>
        <div class="col-md-4" style="text-align: center">
            <h1><?= $title ?></h1>
            <hr class="horizontalLine">
        </div>
        <div class="col-md-4">
            <br>
        </div>
        <div class="col-md-12"><br></div>
        <div class="col-md-2 menu lista">
            <div class="verticalLineRight leftMenuHover"><a href="intro">Úvod</a></div>
            <div class="verticalLineRight leftMenuHover"><a href="vocabulary">Slovník</a></div>
            <div class="verticalLineRight leftMenuHover"><a href="practise">Procvičování</a></div>
            <div class="verticalLineRight leftMenuHover"><a href="myVocabulary">Můj Slovník</a></div>
            <div class="verticalLineRight leftMenuHover"><a href="extendVoc">Rozšířit Slovník</a></div>
            <?php if (isset($_SESSION['user_position']) && $_SESSION['user_position'] == 1) { ?>
                <div class="verticalLineRight leftMenuHover"><a href="maintainVoc">Spravovat Slovník</a></div>
            <?php } ?>
        </div>
        <div class="col-md-8 content">
            <?php foreach ($messages as $message) : ?>
                <p class="zprava"><?= $message ?></p>
            <?php endforeach ?>
            <div>
                <?php $this->controller->buildView(); ?>
            </div>
        </div>
        <div class="col-md-2 lista rightMenuHover">
            <form method="post" class="logout rightMenuHover">
            <?php if (!isset($_SESSION['user_id']) || $_SESSION['user_id'] == 0) {?>
                <div class="verticalLineLeft rightMenuHover"><input type="submit" name="login" value="Přihlášení" /></div>
                <div class="verticalLineLeft rightMenuHover"><input type="submit" name="registration" value="Registrace" /></div>
            <?php } else { ?>
                <div class="verticalLineLeft username"><?php echo $_SESSION['user_name'];?></div>
                <div class="verticalLineLeft rightMenuHover">
                    <input type="submit" name="logout" value="Odhlásit se">
                </div>
            <?php } ?>
            </form>
        </div>
    </div>
</div>
</body>
</html>