<!DOCTYPE html>
<html lang="cz" xmlns:https="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link rel=stylesheet type="text/css" href="resources/styles/bootstrap-4.0.0-alpha.6/dist/css/bootstrap.css"/>
    <link rel=stylesheet type="text/css" href="../resources/styles/style.css"/>


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <link rel=stylesheet type="text/css" href="resources/styles/style.css"/>

    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $key_words ?>" />
</head>
<body>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-4 lista" style="text-align: right">
            <h1><a href="intro">Vocabulary Practice</a></h1>
            <!--<hr class="horizontalLine">-->
        </div>
        <div class="col-md-4" style="text-align: center">
            <h1><?= $title ?></h1>
            <hr class="horizontalLine">
        </div>
        <div class="col-md-4">
            <br>
        </div>
        <div class="col-md-12"><br></div>
        <div class="col-md-2 menu lista leftMenuHover">
            <div class="verticalLineRight"><a href="intro">Úvod</a></div>
            <div class="verticalLineRight"><a href="vocabulary">Slovník</a></div>
            <div class="verticalLineRight"><a href="practise">Procvičování</a></div>
            <div class="verticalLineRight"><a href="myVocabulary">Můj Slovník</a></div>
            <div class="verticalLineRight"><a href="extendVoc">Rozšířit Slovník</a></div>
            <?php if (isset($_SESSION['user_position']) && $_SESSION['user_position'] == 1) { ?>
                <div class="verticalLineRight"><a href="maintainVoc">Spravovat Slovník</a></div>
            <?php } ?>
        </div>
        <div class="col-md-8 content">
            <?php foreach ($messages as $message) : ?>
                <p class="zprava"><?= $message ?></p>
            <?php endforeach ?>
            <div>
                <?php $this->controller->buildView(); ?>
            </div>
        </div>
        <div class="col-md-2 lista rightMenuHover">
            <form method="post" class="logout rightMenuHover">
            <?php if (!isset($_SESSION['user_id']) || $_SESSION['user_id'] == 0) {?>
                <div class="verticalLineLeft"><input type="submit" name="login" value="Přihlášení" /></div>
                <div class="verticalLineLeft"><input type="submit" name="registration" value="Registrace" /></div>
            <?php } else { ?>
                <div class="verticalLineLeft username"><?php echo $_SESSION['user_name'];?></div>
                <div class="verticalLineLeft">
                        <input type="submit" name="logout" value="Odhlásit se">
                </div>
            <?php } ?>
            </form>
        </div>
    </div>
</div>
</body>
</html>